from django.test import TestCase, Client
from django.urls import reverse
from django.utils import timezone

from server.apps.backoffice.forms import sanitize_intro_html
from server.apps.dashboard.models import Edition, Event, Organization


class EditionSlugTestCase(TestCase):
    def setUp(self):
        org = Organization.objects.create(
            name="Org", contact_person="T", contact_email="t@t.nl"
        )
        self.event = Event.objects.create(name="Event", organization=org)

    def _edition(self, name, slug="", mode=Edition.REGISTRATION_QUICK):
        return Edition.objects.create(
            name=name,
            slug=slug,
            event=self.event,
            date_start=timezone.make_aware(timezone.datetime(2026, 6, 1)),
            date_end=timezone.make_aware(timezone.datetime(2026, 6, 2)),
            registration_mode=mode,
        )

    # ── slug generation ─────────────────────────────────────────────

    def test_slug_autogenerated_from_name(self):
        ed = self._edition("Zomertocht 2026!")
        self.assertEqual(ed.slug, "zomertocht-2026")

    def test_explicit_slug_is_kept(self):
        ed = self._edition("Zomertocht", slug="mijn-mooie-url")
        self.assertEqual(ed.slug, "mijn-mooie-url")

    def test_duplicate_name_gets_unique_suffix(self):
        a = self._edition("Herfsttocht")
        b = self._edition("Herfsttocht")
        c = self._edition("Herfsttocht")
        self.assertEqual(a.slug, "herfsttocht")
        self.assertEqual(b.slug, "herfsttocht-2")
        self.assertEqual(c.slug, "herfsttocht-3")

    def test_rename_keeps_existing_slug_stable(self):
        ed = self._edition("Lentetocht")
        original = ed.slug
        ed.name = "Heel Andere Naam"
        ed.save()
        self.assertEqual(ed.slug, original)

    def test_blank_slugifiable_name_falls_back(self):
        ed = self._edition("!!!")
        self.assertEqual(ed.slug, "editie")

    # ── register view resolves by slug ──────────────────────────────

    def test_register_resolves_by_slug(self):
        ed = self._edition("Aanmeldtocht")
        resp = Client().get(reverse("register", args=[ed.slug]))
        self.assertEqual(resp.status_code, 200)

    def test_register_unknown_slug_404(self):
        resp = Client().get("/register/bestaat-niet/")
        self.assertEqual(resp.status_code, 404)

    def test_register_disabled_mode_404(self):
        ed = self._edition("Geen registratie", mode=Edition.REGISTRATION_NONE)
        resp = Client().get(reverse("register", args=[ed.slug]))
        self.assertEqual(resp.status_code, 404)


class IntroSanitizeTestCase(TestCase):
    def test_script_and_handlers_stripped(self):
        dirty = '<p onclick="x()">Hi</p><script>alert(1)</script>'
        clean = sanitize_intro_html(dirty)
        self.assertNotIn("<script", clean)
        self.assertNotIn("onclick", clean)
        self.assertIn("<p>Hi</p>", clean)

    def test_allowed_formatting_kept(self):
        clean = sanitize_intro_html(
            '<strong>Welkom</strong> <a href="https://x.nl">link</a><ul><li>a</li></ul>'
        )
        self.assertIn("<strong>Welkom</strong>", clean)
        self.assertIn('href="https://x.nl"', clean)
        self.assertIn("<li>a</li>", clean)

    def test_javascript_protocol_dropped(self):
        clean = sanitize_intro_html('<a href="javascript:alert(1)">x</a>')
        self.assertNotIn("javascript:", clean)
