DESTINATION_TYPE_MANDATORY = "mandatory"
DESTINATION_TYPE_CHOICE = "choice"
DESTINATION_TYPE_BONUS = "bonus"

DESTINATION_TYPES = [
    (DESTINATION_TYPE_MANDATORY, "Verplicht"),
    (DESTINATION_TYPE_CHOICE, "Keuze"),
    (DESTINATION_TYPE_BONUS, "Bonus"),
]

ROUTE_TYPE_COORDINATE = "coordinate"
ROUTE_TYPE_IMAGE = "image"
ROUTE_TYPE_AUDIO = "audio"

ROUTE_TYPES = [
    (ROUTE_TYPE_COORDINATE, "Coördinaat"),
    (ROUTE_TYPE_IMAGE, "Afbeelding"),
    (ROUTE_TYPE_AUDIO, "Audio"),
]

BUNDLE_BROWSE_FREE = "free"
BUNDLE_BROWSE_LINEAR = "linear"

BUNDLE_BROWSE_MODES = [
    (BUNDLE_BROWSE_FREE, "Vrij bladeren"),
    (BUNDLE_BROWSE_LINEAR, "Lineair (alleen huidig + bezochte)"),
]

BUNDLE_LINEAR_UPCOMING_LOCKED = "locked"
BUNDLE_LINEAR_UPCOMING_HIDDEN = "hidden"

BUNDLE_LINEAR_UPCOMING_MODES = [
    (BUNDLE_LINEAR_UPCOMING_LOCKED, "Vergrendeld (zichtbaar maar geblurred)"),
    (BUNDLE_LINEAR_UPCOMING_HIDDEN, "Verborgen"),
]

FILE_TYPE_IMAGE = "image"
FILE_TYPE_AUDIO = "audio"

FILE_TYPES = [
    (FILE_TYPE_IMAGE, "Afbeelding"),
    (FILE_TYPE_AUDIO, "Audio"),
]
