# Generated by Django 4.2.1 on 2023-06-21 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Edition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("date_start", models.DateTimeField()),
                ("date_end", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="")),
                (
                    "category",
                    models.CharField(
                        choices=[("image", "Afbeelding"), ("audio", "Audio")],
                        default="image",
                        max_length=64,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("contact_person", models.CharField(max_length=255)),
                ("contact_email", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Route",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="routes",
                        to="dashboard.edition",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RoutePart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "route_type",
                    models.CharField(
                        choices=[
                            ("coordinate", "Coördinaat"),
                            ("image", "Afbeelding"),
                            ("audio", "Audio"),
                        ],
                        default="coordinate",
                        max_length=255,
                    ),
                ),
                ("routepart_zoom", models.BooleanField(default=True)),
                ("routepart_fullscreen", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField()),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="routeparts",
                        to="dashboard.route",
                    ),
                ),
                (
                    "routedata_audio",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"category": "audio"},
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="routepart_audio",
                        to="dashboard.file",
                    ),
                ),
                (
                    "routedata_image",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"category": "image"},
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="routepart_images",
                        to="dashboard.file",
                    ),
                ),
            ],
            options={
                "ordering": ["route", "order"],
                "unique_together": {("route", "order")},
            },
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("code", models.CharField(max_length=255)),
                ("contact_name", models.CharField(max_length=100)),
                ("contact_email", models.CharField(max_length=100)),
                ("contact_phone", models.CharField(max_length=100)),
                ("online", models.BooleanField(default=False)),
                (
                    "edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teams",
                        to="dashboard.edition",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="dashboard.organization",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="edition",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="editions",
                to="dashboard.event",
            ),
        ),
        migrations.CreateModel(
            name="Destination",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lat", models.FloatField(max_length=64)),
                ("lng", models.FloatField(max_length=64)),
                ("radius", models.IntegerField()),
                (
                    "destination_type",
                    models.CharField(
                        choices=[
                            ("mandatory", "Verplicht"),
                            ("choice", "Keuze"),
                            ("bonus", "Bonus"),
                        ],
                        default="mandatory",
                        max_length=255,
                    ),
                ),
                ("confirm_by_user", models.BooleanField(default=False)),
                ("hide_for_user", models.BooleanField(default=False)),
                (
                    "routepart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="destinations",
                        to="dashboard.routepart",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TeamRoutePart",
            fields=[
                (
                    "routepart_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="dashboard.routepart",
                    ),
                ),
                (
                    "routepart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teamrouteparts",
                        to="dashboard.routepart",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teamrouteparts",
                        to="dashboard.team",
                    ),
                ),
            ],
            bases=("dashboard.routepart",),
        ),
    ]
