# Generated by Django 4.2.1 on 2023-08-02 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0003_destination_completed"),
    ]

    operations = [
        migrations.CreateModel(
            name="LocationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lat", models.FloatField(max_length=64)),
                ("lng", models.FloatField(max_length=64)),
                ("time", models.DateTimeField(auto_now_add=True)),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="dashboard.team",
                    ),
                ),
            ],
        ),
    ]
