# Generated by Django 4.2.1 on 2023-09-14 19:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0005_routepart_final_teamroutepart_final_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="destination",
            name="completed",
        ),
        migrations.RemoveField(
            model_name="teamroutepart",
            name="completed",
        ),
        migrations.AddField(
            model_name="destination",
            name="completed_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="teamroutepart",
            name="completed_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
