# Generated by Django 4.2.1 on 2025-09-23 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_remove_destination_completed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='radius',
            field=models.IntegerField(),
        ),
    ]
