# Generated by Django 4.2.1 on 2025-09-26 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_destination_radius'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='radius',
            field=models.IntegerField(default=25),
        ),
    ]
