# Generated by Django 4.2.1 on 2026-03-19 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_destination_radius'),
    ]

    operations = [
        migrations.AddField(
            model_name='edition',
            name='registration_confirmation_text',
            field=models.TextField(blank=True, default='', help_text='Confirmation email body for extended registration'),
        ),
        migrations.AddField(
            model_name='edition',
            name='registration_mode',
            field=models.CharField(choices=[('none', 'Uit'), ('quick', 'Snel (naam + e-mail, directe code)'), ('extended', 'Uitgebreid (aanmelding, handmatige activatie)')], default='none', max_length=16),
        ),
        migrations.AddField(
            model_name='team',
            name='contact_address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='team',
            name='is_activated',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='team',
            name='member_names',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='team',
            name='remarks',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='team',
            name='code',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='team',
            name='contact_phone',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
