# Generated by Django 4.2.1 on 2026-03-19 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_add_registration_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('browse_mode', models.CharField(choices=[('free', 'Vrij bladeren'), ('linear', 'Lineair (alleen huidig + bezochte)')], default='free', max_length=20)),
                ('linear_upcoming_mode', models.CharField(choices=[('locked', 'Vergrendeld (zichtbaar maar geblurred)'), ('hidden', 'Verborgen')], default='locked', help_text='Only used when browse_mode is linear', max_length=20)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundles', to='dashboard.route')),
            ],
        ),
        migrations.AddField(
            model_name='routepart',
            name='bundle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routeparts', to='dashboard.bundle'),
        ),
        migrations.AddField(
            model_name='teamroutepart',
            name='bundle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teamrouteparts', to='dashboard.bundle'),
        ),
    ]
