# Generated by Django 4.2.1 on 2026-03-20 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_add_bundle_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='location_update_interval',
            field=models.PositiveIntegerField(default=300, help_text='GPS location upload interval in seconds'),
        ),
    ]
