# Generated by Django 4.2.1 on 2026-03-20 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_add_location_update_interval'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='dashboard.edition')),
                ('recipient_team', models.ForeignKey(blank=True, help_text='Null = broadcast to all teams', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='dashboard.team')),
                ('sender_team', models.ForeignKey(blank=True, help_text='Null = sent by organisation', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='dashboard.team')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
    ]
