# Generated by Django 4.2.1 on 2026-03-21 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_add_message_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='edition',
            name='messaging_enabled',
            field=models.BooleanField(default=False, help_text='Enable messaging between organisation and teams'),
        ),
    ]
