# Generated by Django 4.2.1 on 2026-03-23 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_add_message_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='date',
            field=models.DateField(blank=True, help_text='Optional date for this route. Used to filter location logs on the live map.', null=True),
        ),
    ]
