# Generated by Django 4.2.1 on 2026-03-24 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_create_profiles_for_existing_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
