# Generated by Django 4.2.1 on 2026-05-13 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_add_team_last_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='routepart',
            name='gallery_caption',
            field=models.TextField(blank=True, default='', help_text='Optional text shown above the images on a gallery routepart.'),
        ),
        migrations.AddField(
            model_name='teamroutepart',
            name='gallery_caption',
            field=models.TextField(blank=True, default='', help_text='Optional text shown above the images on a gallery routepart.'),
        ),
        migrations.AlterField(
            model_name='routepart',
            name='route_type',
            field=models.CharField(choices=[('coordinate', 'Coördinaat'), ('image', 'Afbeelding'), ('audio', 'Audio'), ('gallery', 'Galerij')], default='coordinate', max_length=255),
        ),
        migrations.AlterField(
            model_name='teamroutepart',
            name='route_type',
            field=models.CharField(choices=[('coordinate', 'Coördinaat'), ('image', 'Afbeelding'), ('audio', 'Audio'), ('gallery', 'Galerij')], default='coordinate', max_length=255),
        ),
        migrations.CreateModel(
            name='TeamRoutePartImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('image', models.ForeignKey(limit_choices_to={'category': 'image'}, on_delete=django.db.models.deletion.CASCADE, related_name='gallery_teamroutepart_images', to='dashboard.file')),
                ('teamroutepart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='dashboard.teamroutepart')),
            ],
            options={
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='RoutePartImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('image', models.ForeignKey(limit_choices_to={'category': 'image'}, on_delete=django.db.models.deletion.CASCADE, related_name='gallery_routepart_images', to='dashboard.file')),
                ('routepart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='dashboard.routepart')),
            ],
            options={
                'ordering': ('order', 'id'),
            },
        ),
    ]
