# Generated by Django 4.2.1 on 2026-05-14 10:14

from django.db import migrations, models


def remove_gallery_marker_destinations(apps, schema_editor):
    """Remove the (lat=0, lng=0, hide_for_user=True) marker destinations that
    were auto-created for gallery TeamRouteParts before this approach was
    replaced with the gallery_show_immediately flag.
    """
    Destination = apps.get_model("dashboard", "Destination")
    Destination.objects.filter(
        lat=0,
        lng=0,
        hide_for_user=True,
        teamroutepart__route_type="gallery",
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_add_gallery_routepart'),
    ]

    operations = [
        migrations.AddField(
            model_name='routepart',
            name='gallery_show_immediately',
            field=models.BooleanField(default=False, help_text="Gallery only: show the images straight after the previous routepart completes, even when the user is outside the destination radius. User taps 'Door met de route' to confirm."),
        ),
        migrations.AddField(
            model_name='teamroutepart',
            name='gallery_show_immediately',
            field=models.BooleanField(default=False, help_text='Gallery only: show the images straight after the previous routepart completes, even when the user is outside the destination radius.'),
        ),
        migrations.RunPython(
            remove_gallery_marker_destinations,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
